title: Mario Canalella Software Engineer
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
  projects:
    permalink: '/projects/:title/'
layout_style: overflow
palette: blue
header:
  title: Mario Canalella
  tagline: Software Engineer
  profile_img: images/avatar.jpeg
  profile_img_alt: Avatar
  background: dark
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: About
      url: /about/
      style: link
    #- label: Blog
    #  url: /blog/
    #  style: link
    - label: Contact
      url: /contact/
      style: link
  has_social: true
  social_links:
    - label: GitHub
      url: 'https://github.com/'
      style: icon
      icon_class: github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon_class: linkedin
      new_window: true
    - label: Telegram
      url: 'https://dev.to/'
      style: icon
      icon_class: dev
      new_window: true
footer:
  content: >-
    &copy; 2024 Mario Canalella. All rights reserved.
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml